### ISSUE TITLE
Hostel website template

### ISSUE THREAD

**Issue by srinjoy-26** [Abbhiishek/Webners#1]
### Is your feature request related to a problem? Please describe
No

### Describe the solution you'd like
A website template, for finding booking hotels.

### Describe alternatives you've considered
None

### Additional context**
Would add after some time.

**Comment by Abbhiishek** [comment]
Hey @srinjoy-26 ,
Thanks for the raising the issue. Is your project contains only the frontend or you will be managing to deal with some dummy data ?

**Comment by srinjoy-26** [comment]
> Hey @srinjoy-26 , Thanks for the raising the issue. Is your project contains only the frontend or you will be managing to deal with some dummy data ?

Only frontend

**Comment by Abbhiishek** [comment]
okay proceed with the issue @srinjoy-26 
Assigned ✨
Happy contribution
