### ISSUE TITLE
Todo application

### ISSUE THREAD

**Issue by ChandanP007** [Abbhiishek/Webners#12]
A simple todo javascript application built using html, css and javascript. I'll raise issues and want that more features to be added to this simple project. Hope that everyone will contribute in this.

Please add this project for the hacktoberfest22' @Abbhiishek 
Screenshots : 
![image](https://user-images.githubusercontent.com/95927947/193443000-53bfeb44-63e2-4063-93c2-c6a917676452.png)
![image](https://user-images.githubusercontent.com/95927947/193443109-aa68b04f-8fb5-4c95-b1b9-570f3480eff1.png)

**Comment by Abbhiishek** [comment]
Looks good to me ✨
Will assign 
Once you are done make a PR linking this Issue.
