### ISSUE TITLE
Business website header page

### ISSUE THREAD

**Issue by srinjoy-26** [Abbhiishek/Webners#2]
### Is your feature request related to a problem? Please describe
No

### Describe the solution you'd like
A website header page for business related websites.

### Describe alternatives you've considered
None

### Additional context**
![-P](https://user-images.githubusercontent.com/91176055/193330408-7e551b60-cf63-43e2-8e00-23d976a42f4e.png)

**Comment by Abbhiishek** [comment]
Hey @srinjoy-26 ,
Can you share some screenshots or figma design what you gonna achieve

**Comment by srinjoy-26** [comment]
> Hey @srinjoy-26 , Can you share some screenshots or figma design what you gonna achieve

Okk

**Comment by srinjoy-26** [comment]
DONE @Abbhiishek

**Comment by Abbhiishek** [comment]
Go ahead
