### ISSUE TITLE
Tasks can be stored locally.

### ISSUE THREAD

**Issue by ChandanP007** [Abbhiishek/Webners#24]
Hey @Abbhiishek, 
I have come with an idea/feature that if we can store the user tasks locally, then it will allow the users to check their previous completed tasks.
Assign me, if it sounds good to you..
#12

**Comment by Abbhiishek** [comment]
That's a great feature @ChandanP007 
Well how you are planning to implement that?

**Comment by ChandanP007** [comment]
Ah, we can use the localStorage and sessionStorage. So, there will be two options for the user, whether the user wants the task to be saved in the local storage or just for that session only.
