### ISSUE TITLE
Paintry Website

### ISSUE THREAD

**Issue by Asttttha** [Abbhiishek/Webners#27]
Website where creators upload their arts and designs.
This project has a Sign-up page + aboutus page

![179344078-a66bd0be-77dd-4024-9dab-664e909919c0](https://user-images.githubusercontent.com/95849912/193644606-3c67efa1-5229-4c8b-b2ad-149785d0a38f.png)

![179344081-597f4615-5558-43a3-9620-95ed9ac65f1e](https://user-images.githubusercontent.com/95849912/193644827-c530577a-b519-403b-b20f-4774529bf007.png)

**Comment by Abbhiishek** [comment]
Go ahead @Asttttha
