### ISSUE TITLE
Put_Your_Pass - Create and Store your passwords

### ISSUE THREAD

**Issue by Rudresh-pandey** [Abbhiishek/Webners#28]
### Hi, 
**Put_Your_Pass is a static website which will create a strong password (_combinations of alphabets , numbers and special characters_) of your desired length and stores it with your username and application name .**

**### Preview :-**
![image](https://user-images.githubusercontent.com/96531798/193647221-dcd9ece2-bbba-45e7-a3fa-97cd65d3deb9.png)

### **Here is the link to the site  :)** 
https://rudresh-pandey.github.io/Put_Your_Pass/

_will make this project dynamic in future_ 😁

**Comment by Abbhiishek** [comment]
Go ahead @Rudresh-pandey
