### ISSUE TITLE
Pizza Corner

### ISSUE THREAD

**Issue by ilhamansari** [Abbhiishek/Webners#29]
### Is your feature request related to a problem? Please describe
I want to add this project

### Describe the solution you'd like
Online pizza website .

### Describe alternatives you've considered
NA

### Additional context**
NA

**Comment by Abbhiishek** [comment]
Hey @ilhamansari 
Can you show some reference what you are aiming ?

**Comment by ilhamansari** [comment]
Sure @Abbhiishek .  The project is already ready. Here's the glimpse of the project.
![Screenshot (1)](https://user-images.githubusercontent.com/102286043/193821895-25c60e29-57ed-475b-aae4-b378ef0d4540.png)
![Screenshot (2)](https://user-images.githubusercontent.com/102286043/193821918-88a4db42-b5db-497c-b141-f8730b954157.png)

So please assign it to me so that I can create my pr.

**Comment by Abbhiishek** [comment]
Sure go ahead ✨
