### ISSUE TITLE
Official Page Building ✨

### ISSUE THREAD

**Issue by Abbhiishek** [Abbhiishek/Webners#31]
### Is your feature request related to a problem? Please describe
Currently we have an official page with these content. 
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/86338762/193731954-2ab99306-6d71-4f57-86f2-af14009872e9.png">

We want a simple dynamic website which takes all projects and contributors and list them over the site.

### Tech Stack

- React
- Tailwind

We have used Vite for Compiling :)

This is a long term feature and we are seeking help for long term.

**Comment by Rudresh-pandey** [comment]
Hi, i would like to give some UI idea's :)

**Comment by abhishekjis** [comment]
can i work on this 🙏

**Comment by Abbhiishek** [comment]
sure
