### ISSUE TITLE
A Website to list all the contributors 

### ISSUE THREAD

**Issue by Abbhiishek** [Abbhiishek/Webners#4]
### Is your feature request related to a problem? Please describe
We need a dynamic website that list all the contributors and their contribution to this repository.

### Describe the solution you'd like
We suggest to get the data from `CONTRIBUTORS.json` file and render the website.

**Comment by Amarjit-Khan** [comment]
Hey, I would like to create this website.

**Comment by Abbhiishek** [comment]
Sure @Amarjit-Khan 
Go ahead ☺️

**Comment by Amarjit-Khan** [comment]
Can the website be made using react framework?

**Comment by Abbhiishek** [comment]
It's upto you , make sure you include a proper documentation for your code

**Comment by Amarjit-Khan** [comment]
Ok.
