### ISSUE TITLE
GitGood - React app for people to start learning the git cli.

### ISSUE THREAD

**Issue by zaidsidd360** [Abbhiishek/Webners#47]
### Is your feature request related to a problem? Please describe
Using git from the command line can be scary, especially, as a beginner. What's git push and why do we need to add -u or -m with certain commands? This is the problem I'd like to help people with.

### Describe the solution you'd like
In the spirit of open source I want to contribute a react app which will help absolute beginners to get started with the git command line interface.

### Describe alternatives you've considered
NA

### Additional context**
Screenshots
![HeroSection](https://user-images.githubusercontent.com/87397035/195287878-25b1f6a1-3ffb-4749-bddb-ad774c44591f.png)
![MainContent](https://user-images.githubusercontent.com/87397035/195287960-07c62707-c7e4-4457-8990-b917718e0f20.png)

**Comment by zaidsidd360** [comment]
Hey, @Abbhiishek you didn't assign me, should I still go ahead and make the pr?

**Comment by Abbhiishek** [comment]
> Hey, @Abbhiishek you didn't assign me, should I still go ahead and make the pr?

yeah sure go ahead

**Comment by Abbhiishek** [comment]
Code base added

**Comment by Abbhiishek** [comment]
Leave a star to the Repository @zaidsidd360  ⭐

**Comment by zaidsidd360** [comment]
> Leave a star to the Repository @zaidsidd360  ⭐

Sure thing!
