### ISSUE TITLE
Dice Rolling Simulator

### ISSUE THREAD

**Issue by Subha-5** [Abbhiishek/Webners#64]
**Describe the project you want to add with tech stack**
HTML/CSS and JavaScript

**Expected behavior**
A simple project which will ask the user if he or she wants to roll the dice or not. If yes, then the computer will roll a random dice and project its output.

**Additional context**
A program which can be used in a fun way to play dice game with your friends (especially if you doubt the physical dice used )

**Comment by Subha-5** [comment]
@Abbhiishek please assign me this issue

**Comment by Abbhiishek** [comment]
Go ahead @Subha-5
