### ISSUE TITLE
Add Functional Sign up Page

### ISSUE THREAD

**Issue by Nirvik07** [Abbhiishek/Webners#66]
# Tech Stack :
- HTML
- CSS
- JavaScript

# Description
A simple attractive signup page 
![IMG-20221014-WA0001](https://user-images.githubusercontent.com/97960335/195691223-d6f1b38c-48c2-495a-83db-58da3b4f6ce5.jpg)

**Comment by Nirvik07** [comment]
@Abbhiishek assign me this.

**Comment by Abbhiishek** [comment]
Can you share some screenshots

**Comment by Nirvik07** [comment]
@Abbhiishek yes
 I have updated it in the issue description.

**Comment by Abbhiishek** [comment]
Go ahead

**Comment by Nirvik07** [comment]
@Abbhiishek could you put the Hacktoberfest label?
